name: hello again
on:
  push:
    branches:
      - main, develop
jobs:
  helloWorld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: say Hello
        run: echo "Hello world"
        shell: bash
  byebye:
    runs-on: ubuntu-latest
    steps:
        - name: close and clean up
          run: echo "done and dusted"
    


